### ISSUE TITLE
Feature Request: Make Myra Platform Agnostic

### ISSUE THREAD

**Issue by rds1983** [MyraUI/Myra#163]
Make Myra work upon set of abstract interfaces instead of MonoGame/FNA.
Implementing this feature would make it easy to make backends for various C# game frameworks such as Veldrid.

It's not yet decided whether this feature will be implemented.
If you back this idea, then mark this post with corresponding emoji or write a comment. 
If you are against this idea then don't hesistate to react accordingly too.
This case will be realized/rejected depending on amount of support/rejection it'll receive.

**Comment by bernatvadell** [comment]
I'm sure it would implement Raylib if Myra is agnostic platform 👍

**Comment by freever** [comment]
It might be worth looking at the evolving .NET Maui project. It looks like they are building a set of platform-agnostic abstractions for UI components for which renderers are added. Myra could be another set of renderers...?

**Comment by rds1983** [comment]
Implemented & documented: https://github.com/rds1983/Myra/wiki/Using-platform-agnostic-version-of-Myra
