### ISSUE TITLE
Support of different screen sizes

### ISSUE THREAD

**Issue by templarvii** [MyraUI/Myra#165]
I am working on a game for desktop and smartphones. So my game should support large and small screens. My problem is that the UI elements on large screens are too big and on small screens they are too small.

In [GeonBit](https://github.com/RonenNess/GeonBit.UI) there is a feature called [GlobalScale](https://ronenness.github.io/GeonBit.UI-docs/html/P_GeonBit_UI_UserInterface_GlobalScale.htm) which scales all elements. Is there anything similar in Myra?

I could write my own scaling method that changes the size and padding of all elements. Is that the way to do it?

**Comment by rds1983** [comment]
No, Myra doesnt have analogue of GeonBit's GlobalScale. And I must admit that it's indeed good feature.

If you want to write it yourself, take a look at https://github.com/rds1983/Myra/blob/master/src/Myra/Graphics2D/UI/RenderContext.cs

Almost all rendering is done through it. Prbably you can add property Scale there and apply it to all drawing methods(like Opacity is being applied).

**Comment by templarvii** [comment]
I'll have a look at RenderContext.
Thanks a lot.
