### ISSUE TITLE
Box Model (Padding, Border, Margin)

### ISSUE THREAD

**Issue by charles-esterbrook** [MyraUI/Myra#171]
Both CSS and WPF have a concept of Padding, BorderThickness and Margin. In WPF, the type for this is Thickness. Here are some links:

- Padding: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.border.padding?view=netframework-4.8
- BorderThickness: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.border.borderthickness?view=netframework-4.8
- Margin: https://docs.microsoft.com/en-us/dotnet/api/system.windows.frameworkelement.margin?view=netframework-4.8
- Thickness type: https://docs.microsoft.com/en-us/dotnet/api/system.windows.thickness?view=netframework-4.8
- CSS Box Model: https://www.w3schools.com/css/css_boxmodel.asp

I have to admit that from using CSS and WPF, I now think in these terms. I don't see "margin" in the Myra source at all, nor a border on Widget or Container (I guess there is already issue #164).

I recommend:
* Adding a WPF-like Thickness struct
* Replacing `int _paddingLeft, _paddingRight, _paddingTop, _paddingBottom;` with `Thickness _padding;`
* Adding `Thickness _border;` and `Color _borderColor;`
* Adding `Thickness _margin;`
* ... and of course the changes that go with it like the background color not spilling into the margins and MyraPad working correctly

Thoughts?

**Comment by rds1983** [comment]
Hi,
Thanks for the thorough specs.
Most likely eventually it'll be implemented this way.
Though it'll be `IBrush _borderBrush` instead of `Color _borderColor` to make border rendering more flexible.
