### ISSUE TITLE
Feature Request: Have option to shrink-to-fit for Image

### ISSUE THREAD

**Issue by evglabs** [MyraUI/Myra#193]
It'd be great to have an option when assigning a Texture2D to and Image to shrink-to-fit the Texture2D while keeping the aspect ratio.

It'd be useful for displaying Sprites of different sizes in the same space of the GUI.

**Comment by rds1983** [comment]
I've added property ResizeMode to the Image widget. For now it can have two values: Stretch(default) and KeepAspectRatio.

Following vid demonstrates the difference:
![QHSE4Jg87o](https://user-images.githubusercontent.com/1057289/82140671-a91dc300-985a-11ea-809e-8b207b38b6ef.gif)

Original size of sample image is 64x64.
