### ISSUE TITLE
Set button text color

### ISSUE THREAD

**Issue by sk-zk** [MyraUI/Myra#194]
Is it possible to set the text color of buttons independently of the regular label style (with a `Stylesheet` object)?

**Comment by rds1983** [comment]
It is. I think TextButton and ImageTextButton widgets have TextColor property.

**Comment by sk-zk** [comment]
How do I set it from Stylesheet.Current? There's a ButtonStyle but no TextButtonStyle

**Comment by rds1983** [comment]
ButtonStyle is shared by all Button types(TextButton, ImageButton and ImageTextButton).

**Comment by sk-zk** [comment]
Right now I have the same issue but with XML, so I'm just going to add it to this thread

I want to set the text in buttons to a different color than the regular LabelStyle. I've tried this, which seemed the most logical:

```
  <ButtonStyles>
    (...)
    <TextButtonStyle Background="button" OverBackground="button-over" PressedBackground="button-down">
      <LabelStyle Font="default-font" TextColor="white" DisabledTextColor="grey" />
    </TextButtonStyle>
  </ButtonStyles>
```

But it throws an exception: "Class ButtonStyle lacks property marked with ContentAttribute".

**Comment by rds1983** [comment]
Oh, got it. You want to set different text styles for Label and TextButton. No, unfortunately, it's not possible rn.

**Comment by rds1983** [comment]
Now, it's possible to set different text styles for Label and TextButton. ButtonStyle gained LabelStyle property.
Thanks for the great idea!
