### ISSUE TITLE
Update method

### ISSUE THREAD

**Issue by bernatvadell** [MyraUI/Myra#201]
Hi Myra Team!

First of all, thank you for the effort it has taken to develop this library, I was developing something similar when I discovered this repository.

I am migrating my video game to use the Myra interface. Some components of my interface implement animations.

In my current project I had the logic, the Update method. How do you think the best way to deal with this would be with Myra?

The idea would be to change the brush of the Image component every time the index of the active image is updated.

Thanks in advance!

**Comment by rds1983** [comment]
Hello!

Thanks for the kind words too.
Sorry, I didnt quite understand the question.
If you asked about Widget method that is called every frame, then there is virtual method InternalRender that is called every frame for every visible widget. 
Inherit Widget and override InternalRender in order to insert required logic.

**Comment by bernatvadell** [comment]
Thank you! that was what he was looking for.

I am changing it but to make a uniform animation, I am using the GameTime that is passed by parameter in the "Draw" or "Update" method.

At the moment, I have solved it by creating a class "AnimationController" which has a static property with "GameTime".

At the start of the Draw() method, I update the property:

AnimationController.GameTime = gameTime;

And on the InternalRender (overrided), used it.

Is there any other way to recover the value, or is the option proposed appropriate?

Thx!

**Comment by rds1983** [comment]
No, there isnt any other way. You're using perfect workaround. I'd do same on your place.

**Comment by bernatvadell** [comment]
Perfect! ty!
