### ISSUE TITLE
Feature request: Add property BackgroundColor on Widget

### ISSUE THREAD

**Issue by bernatvadell** [MyraUI/Myra#204]
Good Morning!

I need to modify the Background color of a Widget, that is, I have my own implementation of IBrush to render an image.

This implementation receives by parameter the Color to be used for drawing.

I see "Widget" implementation and no value is passing it.

It would be interesting to create a new property in Widget, ex: BackgroundColor, with default value "White" and that is indicated in the drawing method.

![image](https://user-images.githubusercontent.com/17298604/81375680-5594d200-9102-11ea-9c8f-18884fa1031c.png)

What do you think? If that's okay with you, I can do a pull request.

EDIT: Maybe, to avoid confusion, we can do that if Background is NULL and BackgroundColor has a value, then a SolidBrush is created for the background.

**Comment by rds1983** [comment]
Morning!

Frankly I dont want to add a property that copies already existing functionality.
Since you have your own implementation of IBrush, why not add drawing solid background there?

**Comment by bernatvadell** [comment]
At first, I thought about adding the property to my Brush implementation. But it was strange for me to have to indicate the property when it is already informed in the Draw()

![image](https://user-images.githubusercontent.com/17298604/81381797-91816480-910d-11ea-8001-49ab97f95394.png)
