### ISSUE TITLE
Question: Window in static position

### ISSUE THREAD

**Issue by bernatvadell** [MyraUI/Myra#205]
Is possible skip moving a dialog?

I want a fixed dialog...

Ty

**Comment by rds1983** [comment]
No, it's not possible.
I plan to add IsMoveable boolean property to Window.

**Comment by bernatvadell** [comment]
> No, it's not possible.
> I plan to add IsMoveable boolean property to Window.

If u want, i can add for you...

**Comment by rds1983** [comment]
I'd be very grateful for the PR.

**Comment by bernatvadell** [comment]
Well then I get to it.

I have just finished migrating my window to Myra :)

![image](https://user-images.githubusercontent.com/17298604/81419103-ffe61700-914d-11ea-9c0f-493e0d90421f.png)

![image](https://user-images.githubusercontent.com/17298604/81419139-12f8e700-914e-11ea-8478-28eb57f0a3db.png)
