### ISSUE TITLE
Input Displacement/Need Input Hooks

### ISSUE THREAD

**Issue by captkirk88** [MyraUI/Myra#21]
I am having a issue where if I render the GUI to a texture (set to the graphics.BackBufferWidth/Height) and apply the ViewportAdapter's scale matrix, the input is not triggering the controls.
Game.Draw snippet:
```csharp
graphics.GraphicsDevice.Viewport = ViewportAdapter.Viewport;
GraphicsDevice.SetRenderTarget(backBuffer);
// render textures
GraphicsDevice.SetRenderTarget(null);
sb.Begin(SpriteSortMode.Deferred, null, null, null, null, null, ViewportAdapter.GetScaleMatrix());
backBuffer.Draw(sb);
sb.End();
```
Gui render snippet:
```csharp
GUI.Bounds = new Rectangle(0, 0, Game.ViewportAdapter.VirtualWidth, Game.ViewportAdapter.VirtualHeight); // ViewportAdapter from MonoGame.Extended
GUI.Render();
```
Result:
https://i.imgur.com/i80DYmJ.jpg

Everything renders correctly (albeit at a low resolution of 1024x768 to see if it worked), but without a way to hook into the input to modify the mouse position before the GUI checks to see if it is over a control I am locked behind your API.  I am actually trying to create 3d interactable panels  (like a button on a wall) but this was a small test bed to see if it was even possible with your Gui using the default controls.  Please advise on how I would hook into the input subsystem and modify it or at least open it up to allow for a scale to be applied.  I know that there are other options available like creating a custom control, however, to get the full capabilities of your GUI I would have to create duplicates of every control, a approach I would rather avoid.  If that is the only approach, however, what would be the appropriate route?

I am pretty sure this is similar to Issue #19

**Comment by rds1983** [comment]
Thanks for the detailed explanation of the issue.
Yeah, right now, the input handling is very simple: it tracks changes made to the states of keybard/mouse beetween two calls of GUI.Render.
Input hooks are required indeed. Hopefully it'll be fixed in the next version.

**Comment by rds1983** [comment]
Following properties had been added to the Desktop class in the new version 0.5.6:
```c#
		public Func<MouseState> MouseStateGetter { get; set; }
		public Func<KeyboardState> KeyboardStateGetter { get; set; } 
```

**Comment by captkirk88** [comment]
Thank you!
