### ISSUE TITLE
System.MissingMethodException at spriteBatch.DrawRectangle()

### ISSUE THREAD

**Issue by Kolsky** [MyraUI/Myra#211]
Used MonoGame version: MonoGame.Framework.DesktopGL.Core 3.8.0.13
Myra version: 0.9.9.202
Exception details: ```System.MissingMethodException: "Method not found: 'Void Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Microsoft.Xna.Framework.Graphics.Texture2D, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, System.Nullable`1<Microsoft.Xna.Framework.Rectangle>, System.Nullable`1<Microsoft.Xna.Framework.Rectangle>, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, Single, System.Nullable`1<Microsoft.Xna.Framework.Vector2>, System.Nullable`1<Microsoft.Xna.Framework.Color>, Microsoft.Xna.Framework.Graphics.SpriteEffects, Single)'."``` Occurs at spriteBatch.End() call.
Possible reason: some obsolete overloads of Draw method were removed due to reduntancy. FillRectangle works just fine.
(Btw, it's my first issue on github. Tell if I need to provide additional info or structurize it other way.)

**Comment by rds1983** [comment]
Thanks for the report. Definitely it should be fixed before next release.

**Comment by rds1983** [comment]
Seems like MG devs had returned that method in the new release.
I've created simple app that references "MonoGame.Framework.DesktopGL 3.8.0.1375-develop" and "Myra 0.9.9.202". And that app works.
Thus closing.

**Comment by E-Sh4rk** [comment]
I have "MonoGame.Framework.DesktopGL 3.8.0.1375-develop" and "Myra 1.0.0.204" and I am facing the same issue when I call SpriteBatch.DrawRectangle. Calling SpriteBatch.FillRectangle works fine however.
Please let me know if you want more information :)

**Comment by rds1983** [comment]
I've replaced obsolete SpriteBatch.Draw calls with actual ones.
So, guys, if you have a desire, please, check whether the bug is gone with in the latest version(1.0.1.209).

@Kolsky, @E-Sh4rk

**Comment by E-Sh4rk** [comment]
@rds1983 With 1.0.1.209 it works! 👍 Thank you :)
