### ISSUE TITLE
Android Sample Touch Location

### ISSUE THREAD

**Issue by WTRipper** [MyraUI/Myra#217]
I build the Android AllWidget Sample from source and ran it on my S9+ (android 9). It seems that all touch events trigger the click event on the menu bar (File, Edit, Help buttons). I cannot interact with anything else - when I try to it just opens or closes the menu of the File, Edit or Help buttons.

**Comment by WTRipper** [comment]
I ran the debugger today and from a first look I think [this line](https://github.com/rds1983/Myra/blob/bf8efebf9d2b90c7b6c1b56b8edf138c8a04b7c0/src/Myra/Utility/InputHelpers.cs#L16) has to be changed from:  
`return w.Visible && w.Active && w.Enabled && w.ContainsMouse;`  
to  
`return w.Visible && w.Active && w.Enabled && w.ContainsTouch;`  
However I am quite new to the codebase (that was my first look into it) therefore I do not know if there are any side effects. For example it looks like you need another method (e.g. an `CommonMouseCheck`) containing the `.ContainsMouse` check for the `InputHelpers.ProcessMouseMovement` method then.

**Comment by rds1983** [comment]
Thanks for reporting and looking in the issue.
Feel free to make a PR with that proposed line change as well as with new CommonMouseCheck method(that is to be used in the ProcessMouseMovement).
Seems like it would fix the issue.

**Comment by rds1983** [comment]
Tbh, I've some troubles running even android emulator on my current env(ryzen 2600/win 10 home), so can't really fix it by myself.
