### ISSUE TITLE
Floating MessageBox Won't Close

### ISSUE THREAD

**Issue by captkirk88** [MyraUI/Myra#22]
I have the following code for you to test.  I hope I am using your framework correctly.
```csharp
            var button = new Button
            {
                HorizontalAlignment = HorizontalAlignment.Left,
                VerticalAlignment = VerticalAlignment.Center,
                Text = "Show Message Box"
            };

            button.Down += (s, a) =>
            {
                var messageBox = Dialog.CreateMessageBox("Message", "Some message!");
                messageBox.WidthHint = 300;
                messageBox.HeightHint = 100;
                messageBox.Closed += (sender, args) => messageBox.Visible = false;

                GUI.Widgets.Add(messageBox);
            };

GUI.Widgets.Add(button);
```
The message box is added when the button is clicked, however, closing it is impossible.  I have tried variations where I grab the Children and filter by `OfType<Button>` then for each of them hook into the Down event and call the Close method to try to close the message box that way to no avail.  I am stumped.

Adding message boxes the normal way by calling ShowModal works but then I am unable to have multiple MessageBox popups.

**Comment by captkirk88** [comment]
Also, this was tested with v0.5.5.112

**Comment by rds1983** [comment]
Thanks again for the detailed explanation.
This code seems to do the trick:
```
	button.Down += (s, a) =>
	{
		var messageBox = Dialog.CreateMessageBox("Message", "Some message!");
		messageBox.WidthHint = 300;
		messageBox.HeightHint = 100;
		var closeButton = messageBox.TitleGrid.Widgets.OfType<ImageButton>().First();

		closeButton.Up += (sender2, args2) =>
		{
			// Remove is better way than setting Visible to false
			// As setting Visible to false keeps the widget in the list
			GUI.Widgets.Remove(messageBox);
		};

		GUI.Widgets.Add(messageBox);
	};
```
Though, of course, it's an ugly hack. I hope in the upcoming version I'll provide solution for multiple modal windows.

**Comment by captkirk88** [comment]
If it works, I won't complain.  Thanks for the solution.

**Comment by rds1983** [comment]
I've added property CloseButton to Window class in the new version 0.5.6
So above code could be simplified:
```c#
	button.Down += (s, a) =>
	{
		var messageBox = Dialog.CreateMessageBox("Message", "Some message!");
		messageBox.WidthHint = 300;
		messageBox.HeightHint = 100;
		var closeButton = messageBox.CloseButton;

		closeButton.Up += (sender2, args2) =>
		{
			// Remove is better way than setting Visible to false
			// As setting Visible to false keeps the widget in the list
			GUI.Widgets.Remove(messageBox);
		};

		GUI.Widgets.Add(messageBox);
	};
```

**Comment by captkirk88** [comment]
Thank you!

**Comment by rds1983** [comment]
Btw, in the latest Myra(0.6.5) ShowModal adds new dialog to the list of desktop widgets, instead of replacing the existing modal widget. So multiple popups through ShowModal are now allowed.

**Comment by captkirk88** [comment]
Awesome!  Thank you.
