### ISSUE TITLE
MyraPad adds definitions to Windows automatically

### ISSUE THREAD

**Issue by WTRipper** [MyraUI/Myra#221]
I am experiencing some issues while defining Windows in MyraPad. Basically it adds some definitions automatically to the mml which make MyraPad unable to interpret the mml.

**Steps to reproduce:**
1. Build MyraPad from source.
2. Open MyraPad.
3. Create a project with a simple Window in Myrapad or open e.g. "samples\Myra.Samples.NonModalWindows\UI\window1.xml".
4. Save or Format Source will add something like this at the bottom of the Window definition:
```
<Window.DragHandle ColumnSpacing="8">
  <Grid.ColumnsProportions>
    <Proportion Type="Fill" />
    <Proportion Type="Auto" />
  </Grid.ColumnsProportions>
  <Label Text="Window 1" />
  <ImageButton Padding="5" GridColumn="1" />
</Window.DragHandle>
```
5. Error output at the bottom of MyraPad: "Class Widget doesnt have property ColumnsProportions". If you delete the ColumnProportion lines you get "Class Widget lacks property marked with ContentAttribute".

**Comment by rds1983** [comment]
Thanks for the report, the issue had been fixed. If you need to fix existing mml, then simply remove the whole Window.DragHandle block.
