### ISSUE TITLE
How do I add an underscore to menu buttons

### ISSUE THREAD

**Issue by IrishBruse** [MyraUI/Myra#230]
I can change the color but i want it the first letter to be underscored
![image](https://user-images.githubusercontent.com/14964651/86294605-cd581800-bbec-11ea-9ff6-f71f50bd073f.png)

**Comment by rds1983** [comment]
Sorry, it is not possible anymore. The screenshots are outdated.
This feature was in the earlier version, but turn out to be bugged. Thus I've replaced it with colored letter.

**Comment by IrishBruse** [comment]
Well there still seems to be alot of it left in the code you planning on bringing it back cause most applications have the underscore when you hold down alt appears
