### ISSUE TITLE
How can I apply spriteFont to ListItem string?

### ISSUE THREAD

**Issue by greatm84** [MyraUI/Myra#234]
Hello, I'm newbie to Myra and Monogame
Recently  I tried to localization to Monogame
and success to print localization text to my Game

but I failed to find font property to ListItem or so on widgets
how to apply sprite font  to all widgets?
any common ways?

I think very fantastic utility & ui platform Myra library
Thank you!

**Comment by rds1983** [comment]
Hello,
Thanks for kind words regarding Myra.
Unfortunately, there isnt a way to change SpriteFont for the individual ListItem.
But it is possible to change SpriteFont for all ListBoxes using following code(should be called before UI is created):
```c#
  Stylesheet.Current.ListBoxStyle.ListItemStyle.LabelStyle.Font = customFont;
```

Similarly font can be changed for other widgets.
See this wiki entry for more info: https://github.com/rds1983/Myra/wiki/Restyling-Through-Code

**Comment by greatm84** [comment]
Thank you very much ~!
