### ISSUE TITLE
MyraPad 1.0.0.204   automatically  add AcceptsKeyboardFocus property to all Widgets

### ISSUE THREAD

**Issue by greatm84** [MyraUI/Myra#235]
Hello, Awesome Myra
Recently I tried to use MyraPad
Its very useful and awesome
but from Format Source  all export code button
make situation to insert AcceptsKeyboardFocus="True" to all widgets
and it makes display error(blank display)  with  debug line said "Property set ."

Windows 10,   Window mono game project

**Comment by rds1983** [comment]
Hello,
Thanks for reporting. It's known issue and would be fixed in the upcoming release.
