### ISSUE TITLE
Child Elements of Container Inherit Visible Property When Parent's Visible Property Changes

### ISSUE THREAD

**Issue by Nornec** [MyraUI/Myra#239]
I have a set of buttons, each controlling a widget's **visible** property. This should happen one-by-one.
Upon the first press of one of these buttons, the parent container's **visible** property changes to **true** if the parent is not currently visible (by design). When this happens, only one child element should be visible (corresponding to the button pressed), but instead they all have their visible properties set to true. I confirmed this by printing to console the **visible** property of each child before the parent container's **visible** property is set, and then after. Where one child element should be visible, they all are, and their **visible** property is true.

When initializing my child panes, I set their visible property to false.
Widget Hierarchy in this example:
Parent > Child + Child +...
Panel > Grid + Panel +...

Please let me know if you need more information, or if this is intended behavior.

**Comment by rds1983** [comment]
It is indended. I just checked with the WPF(whose behavior Myra tries to mimic), if you change visibility of container there, then the  children visibility changes as well.

**Comment by Nornec** [comment]
Thanks. I've taken this into account and found a work-around for this use case.
