### ISSUE TITLE
Button Keeps Focus

### ISSUE THREAD

**Issue by captkirk88** [MyraUI/Myra#24]
Create a button that shows a message box, yes it is related to what I was doing in the prior issue, then click in a blank area of the game screen and using something like MonoGame.Extended's input framework to capture a key like Escape will not trigger.  In my test TextField is able to relinquish input so it is doing something right.  Button still keeps focus.  This was also evident when creating multiple overlapped message boxes and clicking the close button, the next message boxes close button under the closed message box would not have mouse over indication or the ability to click it until after two clicks.

Not game breaking but I imagine if I was someone playing a game it would be a bit frustrating when reliable input was needed.

**Comment by rds1983** [comment]
Hey @captkirk88,
Sorry, but I didnt understand what is wrong.
I've attached a small sample. It subscribes to the keyboard events using MGE input framework and closes the app on Escape button.
Also it has a Myra's button that spawns MessageBoxes using code from previous issue.
No matter how many MessageBoxes are created and how many time I click on a blank area, the Escape key still works and game closes.
[ButtonFocusGame.zip](https://github.com/rds1983/Myra/files/1559919/ButtonFocusGame.zip)

**Comment by captkirk88** [comment]
Damn.  I am a idiot.  So I have a switch in my Inputs class that sets it to enabled or disabled.  I had it where if the GUI has a FocusedWidget it would disable my input class to allow the GUI to handle the input without doing things like moving the player or camera.  For some reason, FocusedWidget does not go to null if the mouse is clicked on a blank area that has no widgets.  That is what was throwing it off.

**Comment by captkirk88** [comment]
Closing this.  I hacked my way around it.
```csharp
        public void UpdateGUI()
        {
// GUI is just a instance of Desktop
            if (GUI != null && GUI.FocusedWidget != null)
            {
                if (!GUI.FocusedWidget.Bounds.Contains(GUI.MousePosition))
                    GUI.FocusedWidget = null;
            }
        }
```

**Comment by captkirk88** [comment]
Btw calling `GUI.FocusedWidget.IsMouseOver ` does not work.

**Comment by rds1983** [comment]
I see, thanks for explanation.
Btw, Myra has helpful feature for such things called DebugOptionsDialog. It could be shown using this code:
```
var debug = new DebugOptionsDialog();
debug.ShowModal(_host);
```

It'll bring following dialog:
![image](https://user-images.githubusercontent.com/1057289/34026572-a26fb534-e189-11e7-9e27-71e84f2b23a8.png)

Particularry it could be used to highlight the focused widget.

**Comment by captkirk88** [comment]
Good to know.
