### ISSUE TITLE
Images not loading through MML (using FNA)

### ISSUE THREAD

**Issue by Charanor** [MyraUI/Myra#242]
Hello, I'm attempting to load the following MML sheet:

```xml
<Project>
  <Project.ExportOptions />
  <Grid ShowGridLines="True" ColumnSpacing="8" RowSpacing="8" HorizontalAlignment="Left" VerticalAlignment="Bottom">
    <Grid.ColumnsProportions>
      <Proportion Type="Auto" />
      <Proportion Type="Auto" />
    </Grid.ColumnsProportions>
    <Grid.RowsProportions>
      <Proportion Type="Auto" />
      <Proportion Type="Auto" />
    </Grid.RowsProportions>
    <ImageButton Image="hudPlayer_beige.png" Id="spawnUnit1" />
    <Label Text="Spawn Unit 1" HorizontalAlignment="Center" GridRow="1" />
    <ImageButton Image="hudPlayer_blue.png" GridColumn="1" Id="spawnUnit2" />
    <Label Text="Spawn Unit 2" HorizontalAlignment="Center" GridColumn="1" GridRow="1" />
  </Grid>
</Project>
```

However, the images for the `ImageButton`s are not displaying. The rest displays just fine (text, grid lines, etc.). The images are in the same folder as the `.xml` file, structured like this:

```
Content\
  Gui\
    game_ui.xml
    hudPlayer_beige.png
    hudPlayer_blue.png
```

I've tried changing the image path to absolute (`C:\the\dir\Content\Gui\...`), relative to root (`Content\Gui\...`) and relative to `Content.RootDirectory` (`Gui\...`). Nothing seems to change. I'm getting no errors/warnings or anything of the sort. This is the C# code I use to load the xml:

```csharp
// in "LoadContent"
var uiString = File.ReadAllText(Path.Combine("Content", "Gui", "game_ui.xml"));
var project = Project.LoadFromXml(uiString);
desktop = new Desktop {Root = project.Root};

// in "Draw"
desktop.Render();
```

No other image components (`ImageTextButton` etc.) display an image either.

**Comment by Charanor** [comment]
To make it extra clear, the `ImageButton`s are not created at all. I can't click on them or hover over them or anything, and they are not part of the internal DOM of `project.Root`.

**Comment by rds1983** [comment]
Sorry for loading MMLs with external assets not being properly documented.
However if you load such MML, the code should be like:
```c#
  var project = Project.LoadFromXml(uiString, assetManager, Stylesheet.Current);
```

You can read here how to create assetManager: https://github.com/rds1983/XNAssets#creating-assetmanager

**Comment by Charanor** [comment]
Thanks! It works just fine now.
