### ISSUE TITLE
Is it possible to control the default proportions of a SplitPane?

### ISSUE THREAD

**Issue by AridTag** [MyraUI/Myra#245]
Every time I open my application the layout looks like the first image.
But in reality I would like the split panes to look more like the second image by default
![image](https://user-images.githubusercontent.com/1786930/90466031-b60eb480-e0de-11ea-82c8-06760336dcdd.png)
![image](https://user-images.githubusercontent.com/1786930/90466089-da6a9100-e0de-11ea-9b99-569027a2233b.png)

**Comment by rds1983** [comment]
SplitPane has method SetSplitterPosition.
Usage is like
```c#
splitPane.SetSplitterPosition(0, 0.75f);
```

**Comment by AridTag** [comment]
I don't know how I missed that. I guess I was more concerned with looking for proportion like properties, Similar to stackpanels / grids, thank you.
