### ISSUE TITLE
Issue loading UI as described in the wiki

### ISSUE THREAD

**Issue by Hammerstad** [MyraUI/Myra#25]
Hi.

I'm trying to load the UI using the example here: https://github.com/rds1983/Myra/wiki/Using-UI-Editor. I am however unable to find the `Serialization.LoadFromData` method. Searching the repository, I found `Project.LoadFromData`, which did the trick. 

Should the wiki be updated? I'd submit a PR if I could, but it seems like github only accepts PRs for the main repository.

**Comment by rds1983** [comment]
Hi,
Please, submit a PR. I've unchecked 'Restrict edits to collaborators only'.

Btw, I'd recommend trying 'Export To C#' function of the UI Editor(File/Export To C#). It exports UI to the C# code, which could be included in the game project.

**Comment by Hammerstad** [comment]
Thanks.

The wiki does not support PRs, but I've edited the example directly.

And I've also tried the 'Export To C#' function, but for now I'm sticking with the `.ui` files, as it allows for faster prototyping.

Closing the issue as resolved 😄
