### ISSUE TITLE
PropertyGrid not observing source value

### ISSUE THREAD

**Issue by jrunestone** [MyraUI/Myra#251]
I was happy to find a working object editor to use in my debug view and it works fine the way you can directly modify the object with the editors. However I noticed the property grid fields aren't updated when the source object is changing. Is this by design?  I.e. if your "player.position" property changes for some reason (player input for example) the PropertyGrid tied to the "player" object doesn't update its own "position" value.

**Comment by rds1983** [comment]
Yeah, PropertyGrid doesnt watch upon the edited object properties changes.
The only workaround is to refresh it manually using following code:
```c#
  // Set it to the null first. As if we set it to the object it had been set already, then nothing will happen.
  propertyGrid.Object = null;
  propertyGrid.Object = object;
```

**Comment by jrunestone** [comment]
OK not a bug, closing
