### ISSUE TITLE
Issues with 3 TextBlocks wiki tutorial

### ISSUE THREAD

**Issue by damianimmortal** [MyraUI/Myra#26]
I'm getting errors thrown on Widget.DrawFrames = true;
And on
Padding = new PaddingInfo

I'm being told by visual studio that Widget doesn't have DrawFrames and that TextBlock doesn't have a definition for Padding.

**Comment by rds1983** [comment]
Thanks for this issue.
Yeah that tutorial is outdated. Though my nearest plans are to write the thorough documentation for Myra. I'll fix this issue in the process.

**Comment by rds1983** [comment]
Closing due to the fact, there's no 3 TextBlocks tutorial anymore.
