### ISSUE TITLE
Myra Logo

### ISSUE THREAD

**Issue by rds1983** [MyraUI/Myra#273]
Myra needs a logo. If you want to donate one, please, post it into this case.
Btw, the project name came from one ancient city: https://en.wikipedia.org/wiki/Myra

**Comment by rds1983** [comment]
This logo was submitted by discord user B. Coconut(#2834)
![image](https://user-images.githubusercontent.com/1057289/103218718-6bcff680-494e-11eb-9843-ccd37e2fb337.png)

**Comment by peon501** [comment]
nah it looks outdated

**Comment by Gixen** [comment]
Here is my suggestions in different sizes:
![logo512x512](https://user-images.githubusercontent.com/9034838/106715746-c9b2c680-65fd-11eb-92b5-ef0454ecbdfc.png)
![logo256x256x](https://user-images.githubusercontent.com/9034838/106715828-df27f080-65fd-11eb-9be7-06bf47fe2deb.png)
![logo128x128](https://user-images.githubusercontent.com/9034838/106715831-e0591d80-65fd-11eb-8574-dac7ab78fd48.png)
![logo64x64](https://user-images.githubusercontent.com/9034838/106715835-e222e100-65fd-11eb-9660-b7cc31c7a682.png)

Can you see the cat? =3

**Comment by rds1983** [comment]
@Gixen, I can. Thanks for the contribution too! :)

**Comment by rds1983** [comment]
@Gixen,
if it is possible, can you share the PSD source too?

**Comment by Gixen** [comment]
@rds1983 
Absolutley! I'll send them to you over discord
