### ISSUE TITLE
Myrapad: Myrapad doesn't tell us where an error is in either the xmmp file or the styleguide

### ISSUE THREAD

**Issue by LuckyScamper** [MyraUI/Myra#289]
If there is a syntax error or another error (e.g. undeclared variable being called), it causes the file to not being able to load. Fine. However, it also doesn't tell us either in an exception or other methods **why** there is an error. Instead there are KeyNotFoundExceptions in an enclosed assembly.

Any IDE needs an error log that makes it easier for users to track down and resolve issues.

**Comment by rds1983** [comment]
Closing. As this feature is requested at #291
