### ISSUE TITLE
Feature Request: LML

### ISSUE THREAD

**Issue by captkirk88** [MyraUI/Myra#29]
You take a lot of ideas from VisUI and made a great User Interface library.

Is there any chance you will also create a simple Myra Markup Language similar to [gdx-lml](https://github.com/czyzby/gdx-lml/tree/master/lml)?  Or is there anyone with the **time** to take up the challenge?

Online example of gdx-lml in action http://czyzby.github.io/gdx-lml/lml/

**Comment by rds1983** [comment]
Thanks for the feature request. It's unlikely that I'll implement MML. However I would be glad if someone else will.

**Comment by rds1983** [comment]
One step had been made in implementing MML(Myra Markup Language) - Project format became human readable XML.
Example: [allControls.xml](https://github.com/rds1983/Myra/blob/master/samples/Myra.Samples.AllWidgets/allControls.xml)

Also I've wrote a small wiki entry about new and previous Project formats: https://github.com/rds1983/Myra/wiki/MML

**Comment by rds1983** [comment]
Close this issue due to old age and fact that MML had been implemented.
