### ISSUE TITLE
Myrapad: adding Label to a grid throws ''Keynotfoundexception'' inside an unknown dictionary

### ISSUE THREAD

**Issue by LuckyScamper** [MyraUI/Myra#290]
Taken inspiration from https://github.com/rds1983/Myra/blob/master/samples/Myra.Samples.CustomUIStylesheet/allControls.xmmp

`<Project StylesheetPath="stylesheet.xml">
  <Grid RowSpacing="8">    
    <Grid.DefaultRowProportion Type="Auto"/> 
    <Grid.RowsProportions>
       <Proportion Type="Fill" />
       <Proportion Type="Fill" />
       <Proportion Type="Fill" />
    </Grid.RowsProportions>
    <Label Text="Text"  GridRow="0" />
  </Grid>
</Project>`

`<?xml version="1.0" encoding="utf-8" ?>
<Stylesheet TextureRegionAtlas="ui.atlas">
  <DesktopStyle Background="black" />
  <Fonts>
    <Font Id="Trattatello" File="Trattatello.fnt"/>
  </Fonts>
  <LabelStyles>
    <LabelStyle Id="Title" Font="Trattatello" TextColor="white" HorizontalAlignment="Center" />
    <LabelStyle Id="Title-subtext" Font="Trattatello" TextColor="white" HorizontalAlignment="Center" />
  </LabelStyles>
  <ButtonStyles>
    <ButtonStyle Id="MenuButton" Background="button" Width="200" Padding="8" HorizontalAlignment="Center" ContentHorizontalAlignment="Center">
      <LabelStyle Font="Trattatello" TextColor="white" />
    </ButtonStyle>
  </ButtonStyles>
</Stylesheet>`

When I add the Label, it immediately throws the KeyNotFoundException and will continue to do so (and not work) as long as the Label is in the xml code.

**Comment by rds1983** [comment]
Closing. As it's special case of #289
