### ISSUE TITLE
Bug?: TabItem.SelectedChanged only fires on deselect

### ISSUE THREAD

**Issue by minimalism** [MyraUI/Myra#307]
The property setter `TabItem.IsSelected` compares new values with `Button.IsPressed` (via its getter) and early-outs if the value is unchanged, bypassing the `SelectedChanged` event.
When clicking on a tab item to select it, the `Button.IsPressed` value will always be the same as the value received by the property since they originate from the same source.

On deselect however, the `SelectedChanged` event will fire due to the setter logic in `Selector.SelectedItem` calling `_selectedItem.IsSelected = false;` on the previous item.

**Comment by rds1983** [comment]
Yeah, it's a bug.
