### ISSUE TITLE
README.md links to examples lead to a GitHub 404 error

### ISSUE THREAD

**Issue by greenstack** [MyraUI/Myra#309]
Under the Features section of the README, the MML example link leads to a 404 page, as does the example link on the Skinning bullet point.

For the MML example, the link is currently `https://github.com/rds1983/Myra/blob/master/samples/Myra.Samples.AllWidgets/allControls.xml`; it should link to `https://github.com/rds1983/Myra/blob/master/samples/Myra.Samples.AllWidgets/allControls.xmmp`.

For the skinning example, the link is currently `https://github.com/rds1983/Myra/blob/master/samples/Myra.Samples.CustomUIStylesheet/Resources/ui_stylesheet.xml` and it should probably link to `https://github.com/rds1983/Myra/blob/master/samples/Myra.Samples.CustomUIStylesheet/Resources/ui_stylesheet.xml`.

**Comment by rds1983** [comment]
Thanks, fixed.
