### ISSUE TITLE
Widget Remove API Suggestion

### ISSUE THREAD

**Issue by captkirk88** [MyraUI/Myra#31]
Since Widgets keep a reference to the active Desktop, instead of having to do
```csharp
widget.Desktop.Widgets.Remove(widget);
```
I think it would make the api more intuitive to have it as
```csharp
widget.RemoveFromDesktop();
// and for widgets that have a Parent != null also have
widget.RemoveFromParent();
```

And I did notice a lack of a method equivalent to 
```csharp
widget.Children.Remove(Widget widget)
```

**Comment by rds1983** [comment]
Thanks for yet another awesome idea.

> And I did notice a lack of a method equivalent to
> widget.Children.Remove(Widget widget)

Did you mean widget.**Parent**.Children.Remove(Widget widget)?

If you did then, yes, Container(type of Parent property) doesnt allow to add/remove children. However that would be fixed for this issue.

**Comment by captkirk88** [comment]
Yes that is what I meant.  Thank you for taking this on.  I know it could easily be fixed using extension methods on my side but the idea popped in my mind and I thought it would make sense to have it as a part of Widget.
