### ISSUE TITLE
Editing stylesheet in MyraPad shows an error: Mandatory attribute 'TextureRegionAtlas' doesnt exist

### ISSUE THREAD

**Issue by nightblade9** [MyraUI/Myra#319]
I'm following the instructions on the [Editing Stylesheet Using MyraPad](https://github.com/rds1983/Myra/wiki/Editing-Stylesheet-Using-MyraPad) wik page. When I download and unpack the zip and open `allContent.xml` in MyraPad, I get an error: `Mandatory attribute 'TextureRegionAtlas' doesnt exist`

![image](https://user-images.githubusercontent.com/31222662/117569212-936c6380-b092-11eb-83ff-d0dd8f93fb98.png)

**Comment by rds1983** [comment]
Do you use latest Myra(1.2.3)?
As it works for me. The only issue I've encountered is that it couldn't parse color "grey". However it is fixable by replacing "grey" with "gray" in the "default_ui_skin.xml".

**Comment by nightblade9** [comment]
> Do you use latest Myra(1.2.3)?

Yes, I used the latest. I downloaded everything fresh today for the first time, so it's all the latest versions.

**Comment by nightblade9** [comment]
Changing the value to `gray` seems to have resolved that problem. That, or loading and reloading the project several times.

Is it supposed to be this difficult to use? I haven't used Myra before today and I can't figure out how to edit the default styles. Although it's not crashing, all the buttons have a black background and black text, and it's impossible to see if any of my changes have any effect:

![image](https://user-images.githubusercontent.com/31222662/117581795-a13eda80-b0cc-11eb-9ce2-858110db9684.png)

I'm trying to create a style that just changes a couple of things from the default style:

- Set `TextButton` padding to 8
- Set `Panel` background to `#444444FF`

Doesn't seem like there's an easy way to do this in XML, and I can't find a way to do the latter in code, either.

**Comment by rds1983** [comment]
Sorry for the late response. It just stylesheetEdit.zip at wiki was outdated. I've replaced it with the latest version today.

**Comment by nightblade9** [comment]
Yeah, I figured that was it. Thanks for updating the zip.
