### ISSUE TITLE
MyraPad doesn't show suggestion to add MenuItem within MenuItem

### ISSUE THREAD

**Issue by nightblade9** [MyraUI/Myra#320]
I figured out how to make a proper menu with multiple top-level options (File, Edit, etc.) each with their own sub-options when clicked.

It took me about 30 minutes of messing with MyraPad and reading through some of the code to figure out how this works; apparently, you can nest `MenuItem` objects within other `MenuItem` objects:

```xml
<Project>
  <Panel>
    <VerticalStackPanel>
      <HorizontalStackPanel>
        <HorizontalMenu>
          <MenuItem Text="&amp;File">
            <MenuItem Text="&amp;Save" />
            <MenuItem Text="E&amp;xit" />
          </MenuItem>
          <MenuItem Text="&amp;Help">
            <MenuItem Text="&amp;About" />
          </MenuItem>
        </HorizontalMenu>
      </HorizontalStackPanel>
    </VerticalStackPanel>
  </Panel>
</Project>
```

Produces this output:

![image](https://user-images.githubusercontent.com/31222662/117797909-8e3c1f80-b21e-11eb-9022-ff77cb7738e9.png)

It would be great if:

- This could end up as a tutorial/reference on the wiki somewhere
- When you write `<MenuItem></MenuItem>` in MyraPad, and add a new line in the middle, and type `<`, you get an auto-complete item suggesting that you can add another `MenuItem` element.

**Comment by rds1983** [comment]
Thing is you can't nest MenuItems within 2nd level MenuItem(i.e. `<MenuItem Text="&amp;Save" />` in your example). Hence I decided not to add autocomplete in the MyraPad.
Though there are plans to add multilevel nested MenuItems.

**Comment by nightblade9** [comment]
Nested menu items actually does work, as it shows in my screenshot - it just took a lot of trial and error to figure out. But, OK, if you're not planning to add auto-complete, I can just close this.
