### ISSUE TITLE
There is no way to tell Myra.PlatformAgnostic that the game is disposed leading to crashes and graphical glitches.

### ISSUE THREAD

**Issue by KatPurpy** [MyraUI/Myra#322]
If you create a Myra.PlatformAgnostic Desktop, the custom Platform's CreateTexture will be called, that's the expected behaviour.
But when the game instance is disposed, the texture reference **_stays the same but the texture is disposed_**. Due to a design flaw **_it is impossible to tell Myra that the game is disposed_** and the resources must be recreated, that leads to crashes and other glitches that happen when GPU accesses a disposed texture.

**Comment by rds1983** [comment]
I've added public static method `MyraEnvironment.Reset()`. It disposes all default assets and the stylesheet. All widgets created after calling it would use the new instances of the default stylesheet/texture.
