### ISSUE TITLE
Mouse over GUI children childrens

### ISSUE THREAD

**Issue by peon501** [MyraUI/Myra#42]
how can I do check on mouseover for children's in deeper layers dynamically?

**Comment by rds1983** [comment]
Every widget has full set of mouse related events: MouseLeft, MouseEntered, MouseMoved, MouseDown, MouseUp, DoubleClick and MouseWheelChanged.

**Comment by peon501** [comment]
I mean widget widgets too :) or I have to write recursive function for that ??
```

        private bool IsMouseOverGUI()
        {
            VerticalSplitPane toolbar = (VerticalSplitPane) editor.editor.FindWidgetById("toolbar");
            var isMouseOverGUI = false;
            
            foreach(var widget in toolbar.Widgets)
            {
                if (widget.IsMouseOver)
                {
                    isMouseOverGUI = true;
                    break;
                }
            }
            return isMouseOverGUI;
        }
```

**Comment by peon501** [comment]
@rds1983 Basically, I need unlimited depth check if it is inside toolbar :). If main parent is toolbar :)

**Comment by rds1983** [comment]
Oh, I think I got it.
Right now, only Desktop class has IsMouseOverGUI property and it's logic is quite complicated: https://github.com/rds1983/Myra/blob/4f5b6c2a7cc815defb9d0a3c86709108c6929ee4/Source/Myra/Graphics2D/UI/Desktop.cs#L547

As it takes into account many things: is widget is container or not, does it have solid background or not, etc.
I'll think about adding IsMouseOverGUI for any widget.

**Comment by peon501** [comment]
@rds1983 Ty. I will use IsMouseOverGUI :), It will be good enough for my situation :)
