### ISSUE TITLE
Empty properties

### ISSUE THREAD

**Issue by Unimat2809** [MyraUI/Myra#44]
How it is possible to receive coordinates and the sizes of widgets? Everywhere there are zero.

**Comment by rds1983** [comment]
A widget's bounds is stored in the property ActualBounds and is assigned after the first render(as render triggers layout).
So you may try following code to access a widget's bounds:
```C#
// Your Game's Draw method
protected override void Draw(GameTime gameTime)
{
  // Draw UI
  _desktop.Bounds = new Rectangle(0, 0, GraphicsDevice.PresentationParameters.BackBufferWidth, GraphicsDevice.PresentationParameters.BackBufferHeight);
  _desktop.Render();

  // Here you can access widgets' bounds
  var bounds = _widget.ActualBounds.
}
```

**Comment by Unimat2809** [comment]
Ok, Thanks. 
 'first render'  In the debugging mode I saw empty fields - nothing is drawn yet:))
