### ISSUE TITLE
Children

### ISSUE THREAD

**Issue by Unimat2809** [MyraUI/Myra#46]
Hi! 
How can I delete a child member? By code.
I do not understand how RemoveChild works. 
The widget name is necessary?
Important - the name of the child is unknown, a variable.

**Comment by rds1983** [comment]
Try following
```c#
  var widget = container.FindWidgetById(id);
  container.RemoveChild(widget);
```
where `id` is variable with the name of the child.

**Comment by Unimat2809** [comment]
Thanks, but it almost like name. Widgets are created by the code, there are no names, there are no ID. The best option - access Parrent.RemoveChildren[x].
I will change the code so far, to do identical names for removal and replacement of children objects.

P.S. Happy New Year!

**Comment by Unimat2809** [comment]
My option works. My code is read a little worse, but it is not terrible.
Your package very good, one of the few which are loaded at once, without dances with a tambourine.

**Comment by rds1983** [comment]
Hello,

> The best option - access Parrent.RemoveChildren[x].

Btw, Widget already has method RemoveFromParent.

> Your package very good, one of the few which are loaded at once, without dances with a tambourine.

Thanks for the kind words!

> P.S. Happy New Year!

You too! Happy New Year!
