### ISSUE TITLE
Radio button

### ISSUE THREAD

**Issue by Unimat2809** [MyraUI/Myra#49]
Hi! Found in the atlas images for a radio button.
But did not find a radio button in the code.
Made the code. Perhaps, somebody uses.

`            RadioButtonNull = new CheckBox
            {
                Text = "Нулевой участок",
                Image = Myra.DefaultAssets.UISpritesheet["vis-radio-tick-disabled"],
                PressedImage = Myra.DefaultAssets.UISpritesheet["vis-radio-tick"],         
                IsPressed = true,
                GridPositionY = 1
            };
      
            RadioButtonClamp = new CheckBox
            {
                Text = "Одиночные",
                Image = Myra.DefaultAssets.UISpritesheet["vis-radio-tick-disabled"],
                PressedImage = Myra.DefaultAssets.UISpritesheet["vis-radio-tick"],
                IsPressed = false,
                GridPositionY = 2
            };

            RadioButtonSin = new CheckBox
            {
                Text = "Гармонические",
                Image = Myra.DefaultAssets.UISpritesheet["vis-radio-tick-disabled"],
                PressedImage = Myra.DefaultAssets.UISpritesheet["vis-radio-tick"],
                IsPressed = false,
                GridPositionY = 3
            };

            RadioButtonNull.MouseDown += (sender, args) =>
            {
                if (!RadioButtonNull.IsPressed)
                {
                    RadioButtonClamp.IsPressed = false;
                    RadioButtonSin.IsPressed = false;
                   //
                }
                else
                {
                    RadioButtonNull.IsPressed = false;
                }
            };

            RadioButtonClamp.MouseDown += (sender, args) =>
            {
                if (!RadioButtonClamp.IsPressed)
                {
                    RadioButtonNull.IsPressed = false;
                    RadioButtonSin.IsPressed = false;
                   //
                }
                else
                {
                    RadioButtonClamp.IsPressed = false;
                }
            };

            RadioButtonSin.MouseDown += (sender, args) =>
            {
                if (!RadioButtonSin.IsPressed)
                {
                    RadioButtonNull.IsPressed = false;
                    RadioButtonClamp.IsPressed = false;
                    //
                }
                else
                {
                    RadioButtonSin.IsPressed = false;
                }
            };
`

**Comment by rds1983** [comment]
It would be nice to have actual RadioButton in the Myra.
good idea, thanks

**Comment by rds1983** [comment]
RadioButton had been added.
