### ISSUE TITLE
Slider: Make it so clicking somewhere on slider, moves handle there

### ISSUE THREAD

**Issue by rds1983** [MyraUI/Myra#60]

**Comment by tebjan** [comment]
thanks for the issue, but i did not mean to jump the slider there (could be optional with modifier key), but offset with the mouse movement. so only offset the slider when the mouse moves.

**Comment by rds1983** [comment]
thanks for the clarification.
Prob I'll look more into how different GUI frameworks handle that case.
That how it works in WPF:
![wpfslider](https://user-images.githubusercontent.com/1057289/51127073-38762900-1857-11e9-98e7-9f77c143ced4.gif)

**Comment by tebjan** [comment]
ah, interesting. could also be an option. but in my view this is old-school/ms office style and wpf is not the best example for UX. in most media software, especially audio processing, precision is very important. they all only add the mouse movement as offset and often have a modifier to be more precise.

**Comment by rds1983** [comment]
And that's Unity Slider behavior:
![unityslider](https://user-images.githubusercontent.com/1057289/51129925-55622a80-185e-11e9-9901-01d1d664acd9.gif)

Prob I'll do this way.

**Comment by tebjan** [comment]
jump doesn't work well on touchscreens... would not recommend that.

**Comment by rds1983** [comment]
well, then I'll also add an option to turn off jump behavior.
