### ISSUE TITLE
Feature Request: Multiselect ListBox Widget

### ISSUE THREAD

**Issue by Checkman44** [MyraUI/Myra#62]
Hi, we have stumbled upon this nice UI framework. So far we are using it for level editor overlay in MonoGame. 

Would it be possible to add multiselect to existing ListBox or create a MultiselectListBox widget? Selecting multiple game objects would be really handy. Right now we have to use dynamic togglable buttons, which is not so good. 

Thanx much for reply! :)

**Comment by rds1983** [comment]
Hi, thanks for using and liking Myra.
Yes, it would be definitely possible. Probably I'll add property 'SelectionMode' to ListBox, same as in WPF: https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.selectionmode?view=netframework-4.7.2

**Comment by Checkman44** [comment]
That would be really nice! Thanx for the reply.

**Comment by rds1983** [comment]
The proposed functionality had been implemented in the Myra 0.8.5.
ListBox had gained SelectionMode property.
Please, let me know, if there are any problems.

**Comment by rds1983** [comment]
btw, be aware that ListItem.Selected event had been replaced with ListItem.SelectedChanged
Unlike first - which fires only if an item was selected - latter fires when item had been either selected or unselected. ListItem.IsSelected could be used to determine whether item is selected.
