### ISSUE TITLE
How to display Image?

### ISSUE THREAD

**Issue by MaximovInk** [MyraUI/Myra#81]

**Comment by rds1983** [comment]
Hi,
There is corresponding [Image widget](https://github.com/rds1983/Myra/blob/master/src/Myra/Graphics2D/UI/Image.cs)

Renderable property represents its appearance.
You can read about how to set it here: https://github.com/rds1983/Myra/wiki/Texture-Atlas-Framework-and-IRenderable

**Comment by MaximovInk** [comment]
Thanks )
