### ISSUE TITLE
SpinButton increment

### ISSUE THREAD

**Issue by Unimat2809** [MyraUI/Myra#82]
I suggest to add in SpinButton the custom increment.
For himself made simple option. Added new class SpinButton2 (the copy of SpinButton) to the project. 
Added the field:
`private float _increment;
public float Increment
        {
            get { return _increment; }

            set
            {
                if (Integer)
                {
                    _increment = 1;
                }
                else
                {
                    _increment = value;
                    InvalidateMeasure();
                }
            }
        }`
In functions UpButtonOnU()p and DownButtonOnUp() changed lines _++value;_ on _value += _increment;_

In my project works. 
In the editor did not check, did not do such assembly.

**Comment by rds1983** [comment]
Awesome idea!
Wanna send a pull request with that code?

**Comment by Unimat2809** [comment]
In 10 days I will return from work and I will try to finish the code.
