### ISSUE TITLE
SpinButton and MouseWheel

### ISSUE THREAD

**Issue by Unimat2809** [MyraUI/Myra#83]
There is MouseWheelChanged event.
I cannot understand as to use it.
Whether there is an opportunity to change value SpinButton a mouse wheel?

**Comment by rds1983** [comment]
I think MouseWheelChanged event contains delta of the mouse wheel change.
So prob it could be used following way in the SpinButton:
```c#
_spinButton.MouseWheelChanged += (s, a) => 
{
  if(a.Data > 0) 
  {
    _spinButton.Value += someIncrement;
  } else if(a.Data < 0)
  {
    _spinButton.Value -= someIncrement;
  }
};
```

Though probably this functionality deserves to be in SpinButton itself.

**Comment by Unimat2809** [comment]
Tried the similar code. But the event does not work. Put an breakpoint, there is no result.

**Comment by rds1983** [comment]
Seems like a bug. I'll take a look.

**Comment by Unimat2809** [comment]
Forced to work, but having modified the class SpinButton.
I add the file with variable increment and management of a mouse.
In the file the changed fields and functions are commented out. New fields and functions are added at the end.
  **Increment** - is increment of the counter.
  **UpButtonOnUp** and **DownButtonOnUp** - is added the operated increment.
  **Integer** - is added compulsory transfer of Increment to Int.
  **OnMouseWheel ()** - increment for a mouse wheel, it is required to establish SpinButton.CanFocus =  true.
  **Mul_Increment** - "accelerator" increment  for a mouse wheel.
  **Value** - the feature for change of a format of a string is added.
  **FixedNumberSize** - flag for the fixed size of a text field, considers places before and after a dot, and +-.
  **DecimalPlaces** - number of places after a dot.

[SpinButton.zip](https://github.com/rds1983/Myra/files/3100421/SpinButton.zip)

Did not think up how to change the Increment text field in the editor after transition to the Integer mode.

**Comment by rds1983** [comment]
I've added your version of SpinButton to the Myra. Thanks!
SpinButton now works through MouseWheel too,
