### ISSUE TITLE
Caret doesn't stay within clipping bounds

### ISSUE THREAD

**Issue by val-andrushko** [MyraUI/Myra#85]
When typing in a TextField with clipping, caret goes outside of clipping bounds.
I think that caret should always stay in the visible area and visible text should shift instead.

So, for example if we have a string = "This is a very long long string" and TextField can only fit "This is a v" part of it, by typing the rest, the beginning of string should go outside of visible area. Turning visible text into:
"This is a v" +'e' -> "his is a ve"
"his is a ve" + 'r' -> "is is a ver"
Etc. And caret should always stay in the visible area at the right border of TextField.

**Comment by rds1983** [comment]
Now it is possible to make caret stay within clipping bounds if TextField is wrapped in ScrollPane with ShowHorizontalScrollBar set to false.
I.e. following MML:
```xml
<Project>
  <Panel>
    <ScrollPane ShowHorizontalScrollBar="False" HorizontalAlignment="Center" VerticalAlignment="Center" Width="100" >
      <TextField Text="" />
    </ScrollPane>
  </Panel>
</Project>
```

would work following way:
![textField](https://user-images.githubusercontent.com/1057289/62296753-f67e9e80-b499-11e9-9a6c-e53d559449f3.gif)

Though I realize it's workaround. Maybe later I'll come up with fix that wouldnt require TextField to be wrapped into ScrollPane.
Maybe the solution is to merge those two widgets into one. After all, it's unlikely that TextField would be used without ScrollPane.

**Comment by rds1983** [comment]
After looking into how it works in WPF I managed to fix the initial issue without merging TextField with ScrollPanel.
Now above animation works even without ScrollPane.
But even following MML will work:
```xml
<Project>
  <Panel>
    <TextField Text="" HorizontalAlignment="Center" Width="100" VerticalAlignment="Center" />
  </Panel>
</Project>
```
